import os
nodes=[(x,y) for y in range(4) for x in range(4)]
def make_tb(variant):
    dut={'hop':'gold_mesh','xystd':'gold_mesh_xystd','torus':'gold_mesh_torus'}[variant]
    VAR=variant.upper()
    L=[];w=L.append
    w("`timescale 1ns/1ps")
    w("module tb_perf_{};".format(variant))
    w("    parameter CLK_HALF=1,RESET_CYCS=10,NODES=16,MAX_WAIT=5000;")
    w("    reg clk,reset;")
    w("    initial clk=0; always #CLK_HALF clk=~clk;")
    w("    integer cycle_count; initial cycle_count=0;")
    w("    always @(posedge clk) begin")
    w("        if(reset) cycle_count<=0; else cycle_count<=cycle_count+1; end")
    for x,y in nodes:
        n="node{}{}".format(x,y)
        w("    wire {n}_polarity; reg {n}_pesi; wire {n}_peri; reg [63:0]{n}_pedi; wire {n}_peso; reg {n}_pero; wire [63:0]{n}_pedo;".format(n=n))
    w("    wire polarity_arr[0:15],peri_arr[0:15],peso_arr[0:15]; wire [63:0]pedo_arr[0:15];")
    for i,(x,y) in enumerate(nodes):
        n="node{}{}".format(x,y)
        w("    assign polarity_arr[{i}]={n}_polarity; assign peri_arr[{i}]={n}_peri; assign peso_arr[{i}]={n}_peso; assign pedo_arr[{i}]={n}_pedo;".format(i=i,n=n))
    w("    {} dut(.clk(clk),.reset(reset),".format(dut))
    for i,(x,y) in enumerate(nodes):
        n="node{}{}".format(x,y); c="," if i<15 else ""
        w("        .{n}_polarity({n}_polarity),.{n}_pesi({n}_pesi),.{n}_peri({n}_peri),.{n}_pedi({n}_pedi),.{n}_peso({n}_peso),.{n}_pero({n}_pero),.{n}_pedo({n}_pedo){c}".format(n=n,c=c))
    w("    );")
    if variant=='hop':
        w("    function [3:0] unh; input integer n; begin case(n) 0:unh=4'h0;1:unh=4'h1;2:unh=4'h3;default:unh=4'h7; endcase end endfunction")
        w("    function [63:0] make_pkt; input integer sx,sy,dx,dy; input [15:0] ts; reg signed [31:0] ddx,ddy; reg [3:0] hx,hy; reg dirx,diry; reg [7:0] did; begin")
        w("        ddx=dx-sx; ddy=dy-sy; dirx=(ddx<0)?1'b1:1'b0; diry=(ddy>0)?1'b1:1'b0;")
        w("        hx=unh((ddx<0)?-ddx:ddx); hy=unh((ddy<0)?-ddy:ddy); did=dy*4+dx;")
        w("        make_pkt={1'b0,dirx,diry,5'b0,hx,hy,sx[7:0],sy[7:0],did,ts}; end endfunction")
    else:
        w("    function [63:0] make_pkt; input integer sx,sy,dx,dy; input [15:0] ts; reg [7:0] did; begin")
        w("        did=dy*4+dx; make_pkt={1'b0,7'b0,dx[7:0],dy[7:0],sx[7:0],sy[7:0],did,ts}; end endfunction")
    w("    integer pair_latency[0:15][0:15],pair_done[0:15][0:15];")
    w("    integer node_tx_count[0:15],node_tx_lat[0:15],node_rx_count[0:15],node_rx_lat[0:15];")
    w("    integer total_recv,burst_recv,sat_recv; reg [1:0] phase_monitor;")
    w("    integer q_dst[0:15][0:31],q_head[0:15],q_tail[0:15];")
    w("    task enqueue; input integer n,d; begin q_dst[n][q_tail[n]]=d; q_tail[n]=q_tail[n]+1; end endtask")
    w("    integer qi;")
    w("    always @(posedge clk) begin")
    w("        if(reset) begin")
    for x,y in nodes: w("            node{x}{y}_pesi<=1'b0; node{x}{y}_pedi<=64'h0;".format(x=x,y=y))
    w("        end else begin")
    for x,y in nodes: w("            node{x}{y}_pesi<=1'b0;".format(x=x,y=y))
    w("            for(qi=0;qi<16;qi=qi+1)")
    w("                if(q_head[qi]<q_tail[qi]&&polarity_arr[qi]===1'b1&&peri_arr[qi]===1'b1)")
    w("                    case(qi)")
    for i,(x,y) in enumerate(nodes):
        n="node{}{}".format(x,y)
        w("                    {i}: begin {n}_pedi<=make_pkt(qi%4,qi/4,q_dst[qi][q_head[qi]]%4,q_dst[qi][q_head[qi]]/4,cycle_count[15:0]); {n}_pesi<=1'b1; q_head[qi]<=q_head[qi]+1; node_tx_count[qi]<=node_tx_count[qi]+1; end".format(i=i,n=n))
    w("                    endcase")
    w("        end end")
    w("    integer mi; reg [63:0] mpkt; integer msrc,mlat;")
    w("    always @(posedge clk) begin")
    w("        for(mi=0;mi<16;mi=mi+1) if(peso_arr[mi]===1'b1) begin mpkt=pedo_arr[mi];")
    if variant=='hop': w("            msrc=mpkt[47:40]*4+mpkt[39:32];")
    else:              w("            msrc=mpkt[39:32]*4+mpkt[31:24];")
    w("            mlat=cycle_count-mpkt[15:0];")
    w("            if(msrc>=0&&msrc<16&&msrc!=mi) begin")
    w("                if(phase_monitor==0&&!pair_done[msrc][mi]) begin pair_done[msrc][mi]=1; pair_latency[msrc][mi]=mlat; node_tx_lat[msrc]=node_tx_lat[msrc]+mlat; node_rx_count[mi]=node_rx_
    w("                if(phase_monitor==1) burst_recv=burst_recv+1;")
    w("                if(phase_monitor==2) sat_recv=sat_recv+1;")
    w("            end end end")
    w("    integer fhl,fhs,ri,rj,tot_lat,mn_lat,mx_lat,lat_cnt; real avg_lat,at,nt,sl;")
    w("    task write_latency_table; integer c; begin")
    w('        fhl=$fopen("perf_{v}_latency.txt","w"); $fwrite(fhl,"SRC\\\\DST");'.format(v=variant))
    w("        for(c=0;c<16;c=c+1) $fwrite(fhl,\" %4d\",c); $fdisplay(fhl,\"\");")
    w("        for(ri=0;ri<16;ri=ri+1) begin $fwrite(fhl,\" %3d   \",ri);")
    w("            for(rj=0;rj<16;rj=rj+1) if(ri==rj) $fwrite(fhl,\"    -\"); else if(pair_done[ri][rj]) $fwrite(fhl,\" %4d\",pair_latency[ri][rj]); else $fwrite(fhl,\"    ?\");")
    w("            $fdisplay(fhl,\"\"); end $fclose(fhl); end endtask")
    w("    task write_summary; input integer bwin,bpkts,swin,spkts,sr,tcyc; begin")
    w("        tot_lat=0;mn_lat=99999;mx_lat=0;lat_cnt=0;")
    w("        for(ri=0;ri<16;ri=ri+1) for(rj=0;rj<16;rj=rj+1) if(ri!=rj&&pair_done[ri][rj]) begin tot_lat=tot_lat+pair_latency[ri][rj]; if(pair_latency[ri][rj]<mn_lat) mn_lat=pair_latency[ri][rj]; if(pair_latency[ri][rj]>mx_lat) mx_lat=pair_latency[ri][rj]; lat_cnt=lat_cnt+1; end")
    w('        fhs=$fopen("perf_{v}_summary.txt","w"); $fdisplay(fhs,"======================================================");'.format(v=variant))
    w('        $fdisplay(fhs,"  EE577B Cardinal Router -- {V} Performance Report  DUT: {d}");'.format(V=VAR,d=dut))
    w('        $fdisplay(fhs,"======================================================");')
    w('        $fdisplay(fhs,"-- ALL-TO-ALL LATENCY (240 pairs, 1 pkt each) ------");')
    w('        $fdisplay(fhs,"  Pairs measured      : %0d / 240",lat_cnt);')
    w("        if(lat_cnt>0) begin avg_lat=tot_lat*1.0/lat_cnt;")
    w('            $fdisplay(fhs,"  Min latency (cycles): %0d",mn_lat); $fdisplay(fhs,"  Max latency (cycles): %0d",mx_lat); $fdisplay(fhs,"  Avg latency (cycles): %.2f",avg_lat);')
    w('            $fdisplay(fhs,"  Min latency (ns)    : %.1f  (@ 500 MHz sim)",mn_lat*2.0); $fdisplay(fhs,"  Max latency (ns)    : %.1f",mx_lat*2.0); $fdisplay(fhs,"  Avg latency (ns)    : %.1f",avg_lat*2.0); end')
    w('        $fdisplay(fhs,"-- PER-NODE LATENCY BREAKDOWN ----------------------"); $fdisplay(fhs,"  ID  (x,y)   Tx  RxCnt  AvgTxLat  AvgRxLat");')
    w("        for(ri=0;ri<16;ri=ri+1) if(node_tx_count[ri]>0&&node_rx_count[ri]>0)")
    w('            $fdisplay(fhs,"  %2d  (%0d,%0d)  %2d  %5d  %8.2f  %8.2f",ri,ri%4,ri/4,node_tx_count[ri],node_rx_count[ri],node_tx_lat[ri]*1.0/node_tx_count[ri],node_rx_lat[ri]*1.0/node_rx_count[ri]);')
    w('        $fdisplay(fhs,"-- SUSTAINED THROUGHPUT (burst window) -------------"); $fdisplay(fhs,"  Burst window (cycles)   : %0d",bwin); $fdisplay(fhs,"  Packets delivered       : %0d",bpkts);')
    w("        if(bwin>0) begin at=bpkts*1.0/bwin; nt=at/16;")
    w('            $fdisplay(fhs,"  Throughput (pkts/cycle) : %.4f",at); $fdisplay(fhs,"  Norm. tput (pkt/cyc/node): %.4f",nt); $fdisplay(fhs,"  Throughput (Gpkts/s @500MHz): %.4f",at*500.0); end')
    w('        $fdisplay(fhs,"-- SATURATION TEST ---------------------------------"); $fdisplay(fhs,"  Offered window (cycles) : %0d",swin); $fdisplay(fhs,"  Pkts injected (total)   : %0d (all nodes)",spkts); $fdisplay(fhs,"  Pkts received (total)   : %0d",sr);')
    w("        if(swin>0&&spkts>0) begin sl=spkts*1.0/(swin*16);")
    w('            $fdisplay(fhs,"  Offered load            : %.4f pkt/cyc/node",sl); $fdisplay(fhs,"  Accepted throughput     : %.4f pkt/cyc",sr*1.0/swin); end')
    freq={'hop':'258.4','xystd':'259.7','torus':'250.6'}[variant]
    w('        $fdisplay(fhs,"  Max freq: {f} MHz  Total sim cycles: %0d",tcyc); $fdisplay(fhs,"======================================================"); $fclose(fhs); end endtask'.format(f=freq))
    w("    integer ii,jj,ww,bst,ben,bwin,binj,sst,sen,swin,sinj;")
    w("    initial begin")
    w('        $dumpfile("tb_perf_{v}.vcd"); $dumpvars(0,tb_perf_{v});'.format(v=variant))
    w("        reset=1; total_recv=0; burst_recv=0; sat_recv=0; phase_monitor=0; binj=0; sinj=0;")
    for x,y in nodes: w("        node{x}{y}_pero=1'b1; node{x}{y}_pesi=1'b0; node{x}{y}_pedi=64'h0;".format(x=x,y=y))
    w("        for(ii=0;ii<16;ii=ii+1) begin q_head[ii]=0; q_tail[ii]=0; node_tx_count[ii]=0; node_tx_lat[ii]=0; node_rx_count[ii]=0; node_rx_lat[ii]=0;")
    w("            for(jj=0;jj<16;jj=jj+1) begin pair_done[ii][jj]=0; pair_latency[ii][jj]=0; end end")
    w("        repeat(RESET_CYCS) @(posedge clk); @(negedge clk); reset=0; repeat(4) @(posedge clk);")
    w('        $display("[{V}] Phase 1: All-to-all"); phase_monitor=0;'.format(V=VAR))
    w("        for(ii=0;ii<16;ii=ii+1) begin for(jj=0;jj<16;jj=jj+1) if(jj!=ii) enqueue(ii,jj);")
    w("            ww=0; while(q_head[ii]<q_tail[ii]||(total_recv<(ii*15+15)&&ww<MAX_WAIT)) begin @(posedge clk); ww=ww+1; end")
    w("            repeat(12) @(posedge clk); end repeat(20) @(posedge clk);")
    w('        $display("[{V}] Phase 1 done: %0d/240",total_recv);'.format(V=VAR))
    w("        burst_recv=0; for(ii=0;ii<16;ii=ii+1) for(jj=0;jj<16;jj=jj+1) begin enqueue(ii,(ii+jj+1)%16); binj=binj+1; end")
    w("        repeat(4) @(posedge clk); bst=cycle_count; phase_monitor=1;")
    w("        ww=0; begin:wb integer ae; forever begin @(posedge clk); ww=ww+1; ae=1; for(ii=0;ii<16;ii=ii+1) if(q_head[ii]<q_tail[ii]) ae=0; if(ae||ww>5000) disable wb; end end")
    w("        ben=cycle_count; repeat(100) @(posedge clk); phase_monitor=0; bwin=ben-bst;")
    w('        $display("[{V}] Phase 2 done: recv=%0d win=%0d",burst_recv,bwin);'.format(V=VAR))
    w("        sat_recv=0; for(ii=0;ii<16;ii=ii+1) for(jj=0;jj<30;jj=jj+1) begin enqueue(ii,(ii+jj+1)%16); sinj=sinj+1; end")
    w("        repeat(4) @(posedge clk); sst=cycle_count; phase_monitor=2;")
    w("        ww=0; begin:ws integer ae2; forever begin @(posedge clk); ww=ww+1; ae2=1; for(ii=0;ii<16;ii=ii+1) if(q_head[ii]<q_tail[ii]) ae2=0; if(ae2||ww>10000) disable ws; end end")
    w("        sen=cycle_count; repeat(300) @(posedge clk); phase_monitor=0; swin=sen-sst;")
    w('        $display("[{V}] Phase 3 done: inj=%0d recv=%0d win=%0d",sinj,sat_recv,swin);'.format(V=VAR))
    w("        write_latency_table; write_summary(bwin,burst_recv,swin,sinj,sat_recv,cycle_count);")
    w('        $display("[{V}] DONE."); $finish; end'.format(V=VAR))
    w("endmodule")
    return '\n'.join(L)

base='/home/viterbi/09/obhatt/577B/project'
dirs={'hop':base+'/EE577B','xystd':base+'/v2','torus':base+'/v3'}
for v in ('hop','xystd','torus'):
    content=make_tb(v)
    path=dirs[v]+'/tb/tb_perf_{}.v'.format(v)
    with open(path,'w') as f: f.write(content)
    print("Written: "+path)
PYEOF
